codecov:
  notify:
    after_n_builds: 6 # one for each job
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.2%
    patch:
      default:
        enabled: no
        if_not_found: success

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
