---
engines:
  issues:
    exclude_paths:
      - "docs/**"
      - ".github/**"
  complexity:
    exclude_paths:
      - "quacc/tests/**"
      - "docs/**"
      - ".github/**"
  duplication:
    exclude_paths:
      - "quacc/tests/**"
      - "docs/**"
      - ".github/**"
