version = 1

test_patterns = [
  "tests/**",
  "tests_*py"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "prettier"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"
