APPLY_FIXES: all
APPLY_FIXES_EVENT: all
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_GIT_DIFF
  - YAML_PRETTIER
  - YAML_YAMLLINT
EXCLUDED_DIRECTORIES: [.github, tests]
DEFAULT_BRANCH: main
GITHUB_COMMENT_REPORTER: false
PRINT_ALPACA: false
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_PYRIGHT_CONFIG_FILE: pyproject.toml
VALIDATE_ALL_CODEBASE: true
