APPLY_FIXES: all
APPLY_FIXES_EVENT: all
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - JSON_PRETTIER
  - YAML_PRETTIER
EXCLUDED_DIRECTORIES: [.github, tests]
SHOW_SKIPPED_LINTERS: false
VALIDATE_ALL_CODEBASE: true
