APPLY_FIXES: all
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE: pull_request
DISABLE_ERRORS: true
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
EXCLUDED_DIRECTORIES: [.github, tests]
SHOW_SKIPPED_LINTERS: false
VALIDATE_ALL_CODEBASE: true
