APPLY_FIXES: all
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE: pull_request
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
FILTER_REGEX_EXCLUDE: (tests/|.github/)
VALIDATE_ALL_CODEBASE: true
