APPLY_FIXES: all
APPLY_FIXES_EVENT: all
ENABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - REPOSITORY_GIT_DIFF
  - YAML_PRETTIER
EXCLUDED_DIRECTORIES: [.github, tests]
GITHUB_COMMENT_REPORTER: false
VALIDATE_ALL_CODEBASE: true
