name: Bug report
description: Report a bug with quacc.
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: Details about the quacc environment
      description: Please run `quacc info` and paste the output below.
      value: |
        - **quacc version**:
        - **Python version**:
        - **quacc settings**:
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the issue?
      description: A short description of what is going wrong.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How can we easily reproduce the issue?
      description: Provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) of code to reproduce the issue. This is critical. Please do not try to "save time" by omitting it.
    validations:
      required: true
