name: Idea or Feature
description: Propose a new feature to improve quacc.
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: What new feature would you like to see?
      description: A clear and concise description of what you would like added to quacc and why.
    validations:
      required: true
