# We work ase.io.espresso style, but we need to add the namelist keys for each binary.
# !!! For now this is GPT3.5 generated, must be checked !!!

from ase.io.espresso import Namelist

PH_KEYS = Namelist([
    ('input_ph', [
        'amass',
        'outdir',
        'prefix',
        'niter_ph',
        'tr2_ph',
        'alpha_mix',
        'nmix_ph',
        'verbosity',
        'reduce_io',
        'max_seconds',
        'dftd3_hess',
        'fildyn',
        'fildrho',
        'fildvscf',
        'epsil',
        'lrpa',
        'lnoloc',
        'trans',
        'lraman',
        'eth_rps',
        'eth_ns',
        'dek',
        'recover',
        'low_directory_check',
        'only_init',
        'qplot',
        'q2d',
        'q_in_band_form',
        'electron_phonon',
        'el_ph_nsigma',
        'el_ph_sigma',
        'ahc_dir',
        'ahc_nbnd',
        'ahc_nbndskip',
        'skip_upperfan',
        'lshift_q',
        'zeu',
        'zue',
        'elop',
        'fpol',
        'ldisp',
        'nogg',
        'asr',
        'ldiag',
        'lqdir',
        'search_sym',
        'nq1',
        'nq2',
        'nq3',
        'nk1',
        'nk2',
        'nk3',
        'k1',
        'k2',
        'k3',
        'diagonalization',
        'read_dns_bare',
        'ldvscf_interpolate',
        'wpot_dir',
        'do_long_range',
        'do_charge_neutral',
        'start_irr',
        'last_irr',
        'nat_todo',
        'modenum',
        'start_q',
        'last_q',
        'dvscf_star',
        'drho_star',]
    )])

NEB_KEYS = Namelist([
    ('path', [
        'string_method',
        'restart_mode',
        'nstep_path',
        'num_of_images',
        'opt_scheme',
        'CI_scheme',
        'first_last_opt',
        'minimum_image',
        'temp_req',
        'ds',
        'k_max',
        'k_min',
        'path_thr',
        'uses_masses',
        'use_freezing',
        'lfcp',
        'fcp_mu',
        'fcp_thr',
        'fcp_scheme']
    )])

Q2R_KEYS = Namelist([('input', [
        'fildyn',
        'flfrc',
        'zasr',
        'loto_2d',
        'write_lr']
    )])

MATDYN_KEYS = Namelist([
    ('&input', [
        'flfrc',
        'asr',
        'huang',
        'dos',
        'nk1',
        'nk2',
        'nk3',
        'deltaE',
        'ndos',
        'degauss',
        'fldos',
        'flfrq',
        'flvec',
        'fleig',
        'fldyn',
        'at',
        'l1',
        'l2',
        'l3',
        'ntyp',
        'amass',
        'readtau',
        'fltau',
        'la2F',
        'q_in_band_form',
        'q_in_cryst_coord',
        'eigen_similarity',
        'fd',
        'na_ifc',
        'nosym',
        'loto_2d',
        'loto_disable',
        'read_lr',
        'write_frc']
    )])

DYNMAT_KEYS = Namelist([
    ('&input', [
        'fildyn',
        'q',
        'amass',
        'asr',
        'remove_interaction_blocks',
        'axis',
        'lperm',
        'lplasma',
        'filout',
        'fileig',
        'filmol',
        'filxsf',
        'loto_2d',
        'el_ph_nsig',
        'el_ph_sigma']
    )])

# Is this cleaner to import?
ALL_KEYS = {'ph': PH_KEYS, 'neb': NEB_KEYS, 'q2r': Q2R_KEYS, 'dynmat': DYNMAT_KEYS}