name: big-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-big-ubuntu:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install pip packages
        run: |
          pip install --no-cache-dir https://gitlab.com/ase/ase/-/archive/master/ase-master.zip
          pip install .[dev,covalent,defects,jobflow,newtonnet,sella,parsl,prefect,redun,tblite]

      - name: Run tests with pytest
        run: pytest --cov=quacc --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: github.repository == 'Quantum-Accelerators/quacc'

  tests-big-windows:
    strategy:
      fail-fast: true

    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install pip packages
        run: |
          pip install --no-cache-dir https://gitlab.com/ase/ase/-/archive/master/ase-master.zip
          pip install .[dev,defects,jobflow,newtonnet,sella,prefect]

      - name: Run tests with pytest
        run: pytest --cov=quacc --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: github.repository == 'Quantum-Accelerators/quacc'
